const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const code=fs.readFileSync('docs/admin/admin.js','utf8');
function fixture(){
 const nodes=new Map(),events={},calls=[];let auth;
 function node(key){if(!nodes.has(key))nodes.set(key,{textContent:'',value:'',hidden:false,children:[],disabled:false,
  addEventListener(e,f){this[e]=f;},replaceChildren(...values){this.textContent='';this.children=values;},append(...values){this.children.push(...values);}});return nodes.get(key);}
 const client={auth:{onAuthStateChange(f){auth=f;}},rpc(name,args){return new Promise(resolve=>calls.push({name,args,resolve}));}};
 vm.runInNewContext(code,{window:{HubClient:client,addEventListener:(e,f)=>events[e]=f},document:{querySelector:q=>node(q.slice(12,-1)),createElement:tag=>({...node('new-'+nodes.size),children:[],tag})},Date,Number,Error});
 return {node,calls,events,auth:(id,event='SIGNED_IN')=>auth(event,id?{user:{id,email:'owner@example.invalid',user_metadata:{role:'owner'},app_metadata:{role:'owner'}}}:null)};
}
const flush=()=>new Promise(r=>setImmediate(r));
const report=()=>({contractVersion:1,access:{allowed:true},summary:{players:1,sessions:2,activeSeconds:120,matches:1,completedMatches:1,wins:1,losses:0,abandons:0,errors:null},results:[{gameId:"crystal-front-demo",wins:1,losses:0,draws:0,abandons:0,meanScore:50,scoreUnit:"points"}],activity:[{date:'2026-10-03',players:1,sessions:2,activeSeconds:120}],versions:[{gameId:'crystal-front-demo',version:null,buildId:null,sessions:2}],games:[{id:'crystal-front-demo',title:'Crystal <script>alert(1)</script>'}]});
async function allow(s){s.auth('a');s.node('open').click();assert.equal(s.calls[0].name,'lpa_admin_access');s.calls[0].resolve({data:{access:{allowed:true},contractVersion:1}});await flush();s.calls[1].resolve({data:report()});await flush();}
test('anonymous cannot fetch aggregates; forged client roles do not grant access',async()=>{const s=fixture();s.node('open').click();assert.equal(s.calls.length,0);s.auth('ordinary');s.node('open').click();s.calls[0].resolve({data:{access:{allowed:false},contractVersion:1}});await flush();assert.equal(s.calls.length,1);assert.equal(s.node('dashboard').hidden,true);assert.match(s.node('status').textContent,/Нет доступа/);});
test('server-approved read-only report renders real zero and unknown separately',async()=>{const s=fixture();await allow(s);assert.equal(s.node('dashboard').hidden,false);assert.equal(s.node('metrics').children.length,6);assert.match(s.node('errors').textContent,/недоступны/);assert.equal(s.node('results').children[0].children[1].children[0].children[2].textContent,'0');assert.equal(s.node('game').children[1].textContent,'Crystal <script>alert(1)</script>');});
test('late access response after A→B→A cannot reopen dashboard',async()=>{const s=fixture();s.auth('a');s.node('open').click();s.auth('b');s.auth('a');s.calls[0].resolve({data:{access:{allowed:true},contractVersion:1}});await flush();assert.equal(s.calls.length,1);assert.equal(s.node('dashboard').hidden,true);});
test('late report after sign out is discarded and rendered rows cleared',async()=>{const s=fixture();s.auth('a');s.node('open').click();s.calls[0].resolve({data:{access:{allowed:true},contractVersion:1}});await flush();s.auth(null,'SIGNED_OUT');s.calls[1].resolve({data:report()});await flush();assert.equal(s.node('dashboard').hidden,true);assert.equal(s.node('metrics').children.length,0);});
test('closing cabinet preserves account; offline clears and refuses stale responses',async()=>{const s=fixture();await allow(s);s.node('close').click();assert.equal(s.node('dashboard').hidden,true);assert.equal(s.node('open').disabled,false);s.node('open').click();s.events.offline();s.calls[2].resolve({data:{access:{allowed:true},contractVersion:1}});await flush();assert.equal(s.calls.length,3);assert.equal(s.node('dashboard').hidden,true);assert.match(s.node('status').textContent,/интернет/);});
test('RPC errors do not print private details or substitute zero statistics',async()=>{const s=fixture();s.auth('a');s.node('open').click();s.calls[0].resolve({error:{message:'private database detail'}});await flush();assert.equal(s.node('dashboard').hidden,true);assert.equal(s.node('metrics').children.length,0);assert.doesNotMatch(s.node('status').textContent,/private/);assert.match(s.node('status').textContent,/недоступен/);});
test('every report reload rechecks membership and hides old metrics on revocation',async()=>{const s=fixture();await allow(s);s.node('filters').submit({preventDefault(){}});assert.equal(s.calls[2].name,'lpa_admin_access');assert.equal(s.node('dashboard').hidden,true);s.calls[2].resolve({error:{code:'42501'}});await flush();assert.equal(s.calls.length,3);assert.match(s.node('status').textContent,/Нет доступа/);});
test('invalid range sends no request',()=>{const s=fixture();s.auth('a');s.node('from').value='2025-01-01';s.node('to').value='2026-01-01';s.node('open').click();assert.equal(s.calls.length,0);assert.match(s.node('status').textContent,/31 дня/);});
test('standalone route does not load game telemetry or contain privileged keys',()=>{const html=fs.readFileSync('docs/admin/index.html','utf8');assert.doesNotMatch(html,/stats\.js|game-player\.js|service_role/);assert.doesNotMatch(code,/user_metadata|app_metadata|localStorage|sessionStorage|\.email/);assert.match(html,/noindex,nofollow/);});
test('milliseconds results preserve their unit without mixing points',async()=>{const s=fixture();s.auth('a');s.node('open').click();s.calls[0].resolve({data:{access:{allowed:true},contractVersion:1}});await flush();const r=report();r.results[0].scoreUnit='milliseconds';r.results[0].meanScore=10000;s.calls[1].resolve({data:r});await flush();assert.match(s.node('results').children[0].children[1].children[0].children[5].textContent,/мс$/);});
