const fs=require('node:fs'),path=require('node:path');
const {chromium}=require('playwright-core');
const base='https://libertypandaa.github.io/liberty-panda-arcade/';
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 const context=await browser.newContext({serviceWorkers:'block',viewport:{width:1280,height:800}});
 const calls=[], errors=[], screenshots='output/browser-check';fs.mkdirSync(screenshots,{recursive:true});
 await context.route(base+'**',async route=>{
  const u=new URL(route.request().url());const rel=decodeURIComponent(u.pathname.slice(new URL(base).pathname.length));
  let file=path.resolve('docs',rel||'index.html');if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');
  if(!file.startsWith(path.resolve('docs')+path.sep)||!fs.existsSync(file))return route.fulfill({status:404,body:'Not found'});
  await route.fulfill({path:file,contentType:({'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.webmanifest':'application/manifest+json','.png':'image/png'})[path.extname(file)]||'application/octet-stream'});
 });
 await context.route('**/rest/v1/rpc/**',async route=>{
  const headers={'access-control-allow-origin':'*','access-control-allow-headers':'authorization,apikey,x-client-info,content-type,x-supabase-api-version','access-control-allow-methods':'POST,OPTIONS'};
  if(route.request().method()==='OPTIONS')return route.fulfill({status:204,headers});
  const name=route.request().url().split('/').pop();const args=route.request().postDataJSON();calls.push({name,args});
  let data=null;
  if(name==='my_hub_stats')data={launches:calls.filter(x=>x.args?.p_kind==='launch').length,visits:1,lastGame:'clutter-cup',history:[{game:'clutter-cup',created_at:new Date().toISOString()}]};
  if(name==='my_game_stats')data=[];
  await route.fulfill({json:data,headers});
 });
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base,{waitUntil:'networkidle',timeout:120000});
 await page.screenshot({path:screenshots+'/catalog.png',fullPage:true});
 await page.getByRole('button',{name:'Не разрешать',exact:true}).click();
 await page.locator('[data-game-id="clutter-cup"]').click();
 await page.waitForTimeout(12000);
 await page.screenshot({path:screenshots+'/game-no-consent.png'});
 const gameFrame=page.frames().find(f=>f.url().includes('/clutter-cup-playtest/'));
 if(!gameFrame)throw Error('Game iframe missing');
 console.log('GAME UI',await gameFrame.locator('body').innerText());
 if(calls.some(c=>c.name==='record_game_event'))throw Error('Telemetry sent without consent');
 await page.locator('#close-game').click();
 await page.evaluate(()=>{const c=document.querySelector('[data-stats-consent]');c.checked=true;c.dispatchEvent(new Event('change'));});
 await page.locator('[data-game-id="clutter-cup"]').click();
 await page.waitForTimeout(12000);
 await page.screenshot({path:screenshots+'/game-consent.png'});
 for(let attempt=0;attempt<120&&!calls.some(x=>x.name==='record_game_event'&&x.args?.p_name==='ready');attempt++)await page.waitForTimeout(1000);
 const events=calls.filter(x=>x.name==='record_game_event');
 console.log('HANDSHAKE',JSON.stringify({events,errors,state:await page.evaluate(()=>({enabled:window.HubStats?.enabled(),generation:window.HubStats?.context(),consent:localStorage.getItem('lpa:analytics-consent-v2'),checked:document.querySelector('[data-stats-consent]')?.checked,launch:window.HubPlayer?.current()?.url,frame:document.querySelector('#game-frame')?.src}))}));
 await page.screenshot({path:screenshots+'/game-ready.png'});
 if(!events.some(x=>x.args.p_game==='clutter-cup'&&x.args.p_name==='ready'))throw Error('No Clutter Cup ready handshake');
 await page.setViewportSize({width:844,height:430});await page.waitForTimeout(1000);await page.screenshot({path:screenshots+'/landscape.png'});
 const bounds=await page.locator('#game-frame').boundingBox();const close=await page.locator('#close-game').boundingBox();
 if(close.y+close.height>bounds.y+1||bounds.width>844||bounds.y+bounds.height>431)throw Error('Player toolbar overlaps viewport/canvas');
 await page.locator('#close-game').click();
 await page.goto(base+'games/clutter-cup/',{waitUntil:'networkidle'});
 await page.locator('.play-game').click();await page.waitForTimeout(8000);
 await page.screenshot({path:screenshots+'/detail-play.png'});
 await page.locator('#close-game').click();
 await page.goto(base+'games/clutter-cup/install/',{waitUntil:'networkidle'});await page.screenshot({path:screenshots+'/install.png',fullPage:true});
 await page.goto(base+'games/clutter-cup/?launch=phone-shortcut',{waitUntil:'networkidle'});
 if(await page.locator('#game-overlay').getAttribute('hidden')!==null)throw Error('Shortcut did not launch game');
 const report={controlled:true,realGameBuild:true,realDatabase:false,errors,calls,checks:['catalog play','detail play','no consent','SDK ready','landscape toolbar','install page','shortcut launch']};
 fs.writeFileSync(screenshots+'/report.json',JSON.stringify(report,null,2));
 console.log('Browser checks complete',JSON.stringify({errors,events:events.length}));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
