-- Synthetic events only. No changes survive ROLLBACK.
begin;
select set_config('test.guest',gen_random_uuid()::text,true),set_config('test.session',gen_random_uuid()::text,true);
set local role anon;
select public.record_game_event(gen_random_uuid(),current_setting('test.guest')::uuid,current_setting('test.session')::uuid,'crystal-front-demo','session_start','{}');
reset role;
update public.game_analytics_sessions set started_at=now()-interval '1 minute' where id=current_setting('test.session')::uuid;
set local role anon;
do $$
declare a uuid:=current_setting('test.guest')::uuid; s uuid:=current_setting('test.session')::uuid;
  b uuid:=gen_random_uuid(); m uuid:=gen_random_uuid(); eid uuid:=gen_random_uuid(); rejected boolean; r jsonb;
begin
  perform public.record_game_event(gen_random_uuid(),a,s,'crystal-front-demo','ready','{"load_ms":100}');
  perform public.record_game_event(gen_random_uuid(),a,s,'crystal-front-demo','ready','{"load_ms":200}');
  perform public.record_game_event(eid,a,s,'crystal-front-demo','active_time','{"seconds":15}');
  perform public.record_game_event(eid,a,s,'crystal-front-demo','active_time','{"seconds":15}');
  perform public.record_game_event(gen_random_uuid(),a,s,'crystal-front-demo','match_start',jsonb_build_object('match',m,'mode','duel'));
  perform public.record_game_event(gen_random_uuid(),a,s,'crystal-front-demo','match_end',jsonb_build_object('match',m,'outcome','win','score',120));
  perform public.record_game_event(gen_random_uuid(),a,s,'crystal-front-demo','match_end',jsonb_build_object('match',m,'outcome','win','score',120));
  perform public.record_game_event(gen_random_uuid(),a,s,'crystal-front-demo','tutorial','{"step":"intro","state":"start"}');
  perform public.record_game_event(gen_random_uuid(),a,s,'crystal-front-demo','tutorial','{"step":"intro","state":"complete"}');
  perform public.record_game_event(gen_random_uuid(),a,s,'crystal-front-demo','progress','{"level":"one","percent":50}');
  perform public.record_game_event(gen_random_uuid(),a,s,'crystal-front-demo','achievement','{"achievement":"first_win"}');
  perform public.record_game_event(gen_random_uuid(),a,s,'crystal-front-demo','achievement','{"achievement":"first_win"}');
  perform public.record_game_event(gen_random_uuid(),a,s,'crystal-front-demo','custom','{"name":"bomb_used","value":1}');
  perform public.record_game_event(gen_random_uuid(),a,s,'crystal-front-demo','error','{"code":"assets_failed"}');
  r:=public.my_game_stats(a)->0;
  if r->>'activeSeconds'<>'15' or r->>'loaded'<>'1' or r->>'wins'<>'1' or r->>'achievements'<>'1' or r->>'errors'<>'1' then raise exception 'Counts/dedup failed: %',r; end if;
  if r->'tutorial'->0->>'completed'<>'1' or (r->'progress'->0->>'average_best_percent')::numeric<>50 or r->'custom'->0->>'total'<>'1' then raise exception 'Aggregates failed'; end if;
  if public.my_game_stats(b)<>'[]'::jsonb or public.my_game_stats(null)<>'[]'::jsonb then raise exception 'Guest data leaked'; end if;
  rejected:=false;
  begin perform public.record_game_event(gen_random_uuid(),b,s,'crystal-front-demo','ready','{"load_ms":1}'); exception when others then rejected:=true; end;
  if not rejected then raise exception 'Cross-guest write accepted'; end if;
  rejected:=false;
  begin perform public.record_game_event(gen_random_uuid(),a,s,'crystal-front-demo','custom','{"name":"unknown","value":1}'); exception when others then rejected:=true; end;
  if not rejected then raise exception 'Unknown custom accepted'; end if;
  rejected:=false;
  begin perform public.record_game_event(gen_random_uuid(),a,s,'crystal-front-demo','progress','{"level":"one","percent":101}'); exception when others then rejected:=true; end;
  if not rejected then raise exception 'Invalid progress accepted'; end if;
  rejected:=false;
  begin perform public.record_game_event(gen_random_uuid(),a,s,'crystal-front-demo','ready','{"load_ms":1,"email":"private"}'); exception when others then rejected:=true; end;
  if not rejected then raise exception 'Extra fields accepted'; end if;
  begin perform public.game_stats_for(null); raise exception 'Internal report exposed'; exception when insufficient_privilege then null; end;
  begin perform 1 from public.game_analytics_sessions; raise exception 'Table exposed'; exception when insufficient_privilege then null; end;
  begin perform public.admin_game_stats(); raise exception 'Admin exposed'; exception when insufficient_privilege then null; end;
  perform public.record_game_event(gen_random_uuid(),a,s,'crystal-front-demo','session_end','{}');
  perform public.record_game_event(gen_random_uuid(),a,s,'crystal-front-demo','error','{"code":"after_close"}');
  if public.my_game_stats(a)->0->>'errors'<>'1' then raise exception 'Closed session accepted event'; end if;
  perform public.delete_my_hub_stats(a);
  if public.my_game_stats(a)<>'[]'::jsonb then raise exception 'Deletion incomplete'; end if;
end;
$$;
reset role;
select set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',true);
set local role authenticated;
do $$ begin
  begin perform public.admin_game_stats(); raise exception 'Non-owner report exposed'; exception when insufficient_privilege then null; end;
end; $$;
reset role;
select set_config('request.jwt.claim.sub',(select user_id::text from public.hub_analytics_admins limit 1),true);
set local role authenticated;
select public.admin_game_stats() is not null as owner_report;
rollback;
select 'PASS: game aggregates, duplicates, session ownership, schema validation, private reports, deletion' as result;
